// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQ7FwdcwCaOjr1GK7MIMzPKk2vXDPJ3s',
    appId: '1:419300768456:web:2a81ac37e3764bbc7d43fd',
    messagingSenderId: '419300768456',
    projectId: 'barberturno-d3ec6',
    authDomain: 'barberturno-d3ec6.firebaseapp.com',
    storageBucket: 'barberturno-d3ec6.firebasestorage.app',
    measurementId: 'G-5LVVRPZDDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLUEGWBXu0p3DoIx-1ZW9Y8JQLZuqg48c',
    appId: '1:419300768456:android:b6e4441f072853ba7d43fd',
    messagingSenderId: '419300768456',
    projectId: 'barberturno-d3ec6',
    storageBucket: 'barberturno-d3ec6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-exLMuMc6nq6iCx5QosskAnP7TQiE9RI',
    appId: '1:419300768456:ios:325e3da5b19545ff7d43fd',
    messagingSenderId: '419300768456',
    projectId: 'barberturno-d3ec6',
    storageBucket: 'barberturno-d3ec6.firebasestorage.app',
    iosBundleId: 'com.barberturno.app',
  );
}
